version: '3.8'

services:
  wake-word-test:
    build: .
    container_name: wake-word-test
    command: python3 -m hey_orac.wake_word_detection
    restart: unless-stopped
    
    # Audio device access
    devices:
      - /dev/snd:/dev/snd
    
    # Privileged mode for audio hardware access
    privileged: true
    
    # Volume mounts
    volumes:
      - ./src:/app/src  # Mount source code for live updates
      - ./logs:/app/logs
      - ./recordings:/app/recordings
      - /tmp:/tmp
      # Cache downloaded OpenWakeWord models
      - ./model_cache:/home/appuser/.local/share/openwakeword
      # Mount custom TFLite models
      - ./models:/app/models
      # Mount config directory for settings.json
      - ./config:/app/config
    
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - ALSA_CARD=1
      - AUDIO_DEVICE=/dev/snd
      - PULSE_RUNTIME_PATH=/tmp
    
    # Port mappings for web GUI
    ports:
      - "7171:7171"
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import openwakeword; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits (adjust for your Pi)
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M