version: '3.8'

services:
  hey-orac:
    build:
      context: .
      dockerfile: docker/Dockerfile
      cache_from:
        - hey-orac_hey-orac:latest
    container_name: hey-orac
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # Mount audio devices
      - /dev/snd:/dev/snd:rw
      # Mount ALSA configuration
      - ./asound.conf:/etc/asound.conf:ro
      - /usr/share/alsa:/usr/share/alsa:ro
      - /etc/alsa:/etc/alsa:ro
      # Mount configuration for easy updates
      - ./src/config.yaml:/app/config.yaml:ro
      # Mount models directory
      - ./models:/app/models:ro
      # Mount logs directory
      - ./logs:/app/logs
    devices:
      # Access to audio devices
      - /dev/snd:/dev/snd
      # Access to USB devices (for USB microphones)
      - /dev/bus/usb:/dev/bus/usb
    group_add:
      - audio
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:0
      # ALSA configuration
      - ALSA_CARD=0
      - ALSA_DEVICE=0
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    ulimits:
      memlock: -1
      stack: 67108864
    privileged: true
    security_opt:
      - no-new-privileges:false
    cap_drop:
      - ALL
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  hey-orac-network:
    driver: bridge

volumes:
  logs:
    driver: local 