# Audio settings
audio:
  mic_index: 0                    # USB microphone device index
  sample_rate: 16000             # Audio sample rate
  channels: 1                     # Mono audio
  chunk_size: 512                 # Audio chunk size for processing

# Wake-word settings
wake_word:
  engine: "openwakeword"         # Engine to use: "porcupine", "openwakeword", "snowboy", "pocketsphinx", "test"
  model_path: /app/models/porcupine/orac.ppn
  sensitivity: 0.6               # Detection sensitivity (0.0-1.0) - for Porcupine
  keyword: "hey_jarvis"          # Wake-word to detect (using pre-trained OpenWakeWord models)
  access_key: ""                 # Picovoice access key (get from console.picovoice.ai)
  
  # OpenWakeWord settings (only used when engine="openwakeword")
  threshold: 0.001               # Detection threshold (0.0-1.0) - very low for testing
  custom_model_path: "third_party/openwakeword/custom_models/Hay--compUta_v_lrg.onnx"  # Custom "Hey Computer" model
  
  # Test engine settings (only used when engine="test")
  detection_probability: 0.01    # Probability of detection per audio chunk
  min_detection_interval: 2.0    # Minimum seconds between detections

# Buffer settings
buffer:
  preroll_seconds: 1.0           # Audio to capture before wake-word
  postroll_seconds: 2.0          # Audio to capture after wake-word
  max_duration: 4.0              # Maximum audio clip duration

# Network settings
network:
  jetson_endpoint: http://jetson-orin:8000/speech
  timeout_seconds: 5.0           # HTTP request timeout
  retry_attempts: 3              # Number of retry attempts

# Logging
logging:
  level: INFO                     # Log level (DEBUG, INFO, WARNING, ERROR) - temporarily INFO to debug
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: /app/logs/hey-orac.log

# Volume monitoring settings (for optimized pipeline)
volume_monitoring:
  silence_threshold: 100         # RMS threshold for silence detection
  window_size: 10                # Number of samples for volume trend analysis

# Performance
performance:
  cpu_affinity: null             # CPU core affinity (null for auto)
  memory_limit_mb: 200           # Memory limit in MB

# Global settings for web interface
global:
  cooldown_s: 1.5
  debounce_ms: 200
  rms_filter: 50

# Model settings for web interface
models:
  Hay--compUta_v_lrg:
    api_url: https://api.example.com/webhook
    sensitivity: 0.05
  Hey_computer:
    api_url: https://api.example.com/webhook
    sensitivity: 0.05
  hey-CompUter_lrg:
    api_url: https://api.example.com/webhook
    sensitivity: 0.05 