# Audio settings
audio:
  mic_index: 0                    # USB microphone device index
  sample_rate: 16000             # Audio sample rate
  channels: 1                     # Mono audio
  chunk_size: 512                 # Audio chunk size for processing

# Wake-word settings
wake_word:
  engine: "openwakeword"         # Engine to use: "porcupine", "openwakeword", "snowboy", "pocketsphinx", "test"
  model_path: /app/models/porcupine/orac.ppn
  sensitivity: 0.6               # Detection sensitivity (0.0-1.0) - for Porcupine
  keyword: "hey_computer"        # Wake-word to detect (using custom OpenWakeWord model)
  access_key: ""                 # Picovoice access key (get from console.picovoice.ai)
  
  # OpenWakeWord settings (only used when engine="openwakeword")
  threshold: 0.1                 # Detection threshold (0.0-1.0) - lowered for testing
  custom_model_path: "/app/third_party/openwakeword/custom_models/Hey_computer.onnx"  # Custom model path
  
  # Test engine settings (only used when engine="test")
  detection_probability: 0.01    # Probability of detection per audio chunk
  min_detection_interval: 2.0    # Minimum seconds between detections

# Buffer settings
buffer:
  preroll_seconds: 1.0           # Audio to capture before wake-word
  postroll_seconds: 2.0          # Audio to capture after wake-word
  max_duration: 4.0              # Maximum audio clip duration

# Network settings
network:
  jetson_endpoint: http://jetson-orin:8000/speech
  timeout_seconds: 5.0           # HTTP request timeout
  retry_attempts: 3              # Number of retry attempts

# Logging
logging:
  level: INFO                    # Log level (DEBUG, INFO, WARNING, ERROR)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: /app/logs/hey-orac.log

# Performance
performance:
  cpu_affinity: null             # CPU core affinity (null for auto)
  memory_limit_mb: 200           # Memory limit in MB 